# Jykell configuration
# markdown: redcarpet
# redcarpet:
#   syntax_highlighter_opts:
#     disable: true

# highlighter: pygments
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
  auto_ids: true
  input: GFM
  toc_levels: 1..2

highlighter: none
# highlighter: rouge
paginate: 30
language: 'en-uk'

# Website info
name: 'Draveness'
description: "分析路径中"

# Author's info
author: 'Draveness'
# edit 'categories' in the front matter of every post to match this username
nickname: draveness
bio: 'Rails / Elixir / iOS'
location: 'Maine, USA'
url: 'http://draveness.me'
img_url: 'http://img.draveness.me'
image: 'assets/images/draven.png'

short_url: 'draveness.me'
google_analytics: UA-56898419-1
disqus: draveness
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
# permalink: /:title
permalink: pretty
# permalink: /tag/:tag

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - octopress-minify-html
whitelist:
  - jekyll-redirect-from

exclude: [vendor]

sass:
  style: compressed

safe: false
lsi: false
username: draveness
repo: jekyll-blog
branch: master
relative_source: ../jasper/
destination: ../jasper-pages/
production_url:  https://biomadeira.github.io/jasper/
source_url:      https://github.com/biomadeira/jasper/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

theme: jekyll-theme-cayman
